Repository scientific-python/devstats, pull requests merged in 2023-07, with the labels that each got.

#20 Use label-check and attach-next-milestone-action
  .github/workflows/label-check.yaml
  .github/workflows/milestone-merged-prs.yaml
Labels: type: Maintenance

#21 Specify what goes in sdist
  CHANGELOG.md
  MANIFEST.in
  pyproject.toml
Labels: type: Maintenance

#22 Use changelist
  RELEASE.md
  pyproject.toml
Labels: type: Maintenance

#23 Used dependabot
  .github/dependabot.yml
Labels: type: Maintenance

#25 Publish from templates
  devstats/.gitignore
  devstats/__main__.py
  devstats/publish.py
  devstats/reports/index.md
  devstats/reports/issue_first_responders.md
  devstats/reports/issue_time_to_response.md
  devstats/reports/new_issues.md
  devstats/reports/preamble.md
  devstats/reports/prs_contributor_origin.md
  devstats/reports/prs_lifetime.md
  devstats/reports/prs_mergeability.md
  devstats/reports/prs_merged_over_time.md
  devstats/reports/prs_participants.md
  devstats/reports/prs_pony_factor.md
  devstats/template.md
Labels: type: Enhancement

#26 Fetch data needed for circlci
  .circleci/config.yml
Labels: type: Bug fix

#27 Point redirector to correct location
  .github/workflows/circleci.yml
Labels: type: Bug fix

#28 Add pre-commit badge
  README.md
Labels: type: Documentation
