Repository scientific-python/devstats, pull requests merged in 2025-05, with the labels that each got.

#84 Strip timezone offset to avoid NumPy warning
  devstats/reports/issue_time_to_response.md
  devstats/reports/new_issues.md
Labels: type: Bug fix

#86 fix rstrip
  devstats/reports/issue_time_to_response.md
Labels: type: Bug fix

#85 remove duplicated files
  devstats/reports/issues/first_responders.md
  devstats/reports/issues/new_issues.md
  devstats/reports/issues/time_to_response.md
  devstats/reports/pull_requests/mergeability_of_open_prs.md
  devstats/reports/pull_requests/merged_prs_over_time.md
  devstats/reports/pull_requests/number_of_pr_participants.md
  devstats/reports/pull_requests/pony_factor.md
  devstats/reports/pull_requests/pr_lifetime.md
  devstats/reports/pull_requests/where_contributions_come_from.md
Labels: type: Maintenance

#89 store data for when user stars the repo
  devstats/__main__.py
Labels: type: Enhancement

#71 Reduce dependencies
  README.md
  pyproject.toml
Labels: type: Maintenance

#90 record the start and end date of the query
  devstats/__main__.py
  devstats/queries/issue_activity_since_date.gql
  devstats/query.py
Labels: type: Enhancement

#91 record the repo and repo owner
  devstats/__main__.py
Labels: type: Enhancement
